language: cpp
matrix:
  include:
    - os: linux
      compiler: gcc
    - os: osx
      compiler: clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../mp2-lab1-set
  - make -j
  - ./bin/test_set --gtest_list_tests
notifications:
  email: false
